mymoney/money/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('docs', DocumentList.as_view(), name='docs'),
    path('doc/<int:doc_id>', show_doc, name='show_doc'),
    path('add_debit_doc', add_debit_doc, name='add_debit_doc'),
    path('add_credit_doc', add_credit_doc, name='add_credit_doc'),
    path('delete_doc/<int:doc_id>/', delete_doc, name='delete_doc'),
    path('dirs', directories, name='dirs'),
    path('ctr_list', CounterpartyList.as_view(), name='ctr_list'),
    path('rates_list', ExchangeRatesList.as_view(), name='rates_list'),
    path('add_rate', AddExchangeRates.as_view(), name='add_rate'),
    path('show_rate/<int:rate_id>/', show_rate, name='show_rate'),
    path('delete_rate/<int:rate_id>/', delete_rate, name='delete_rate'),
    path('show_counterparty/<int:contr_id>/', show_counterparty, name='show_counterparty'),
    path('delete_counterparty/<int:contr_id>/', delete_counterparty, name='delete_counterparty'),
    path('add_counterparty', AddCounterpartyForm.as_view(), name='add_counterparty'),
    path('add_currencie', AddCurrencieForm.as_view(), name='add_currencie'),
    path('cur_list', CurrenciesList.as_view(), name='cur_list'),
    path('delete_currencie/<slug:curr_id>/', delete_currencie, name='delete_currencie'),
    path('show_currencie/<slug:curr_id>/', show_currencie, name='show_currencie'),
    path('category_list', CategoryList.as_view(), name='category_list'),
    path('add_category', AddCategoryForm.as_view(), name='add_category'),
    path('show_category/<int:category_id>/', show_rate, name='show_category'),
    path('delete_category/<int:category_id>/', delete_category, name='delete_category'),
    path('monacn_list', MoneyAccountList.as_view(), name='monacn_list'),
    path('add_monacc', AddMoneyAccount.as_view(), name='add_monacc'),
    path('show_monacc/<int:monacc_id>/', show_money_account, name='show_monacc'),
    path('delete_monacc/<int:monacc_id>/', delete_monacc, name='delete_monacc'),
    #reports
    path('reports', reports, name='reports'),
    path('report_dynamic_money', report_dynamic_money, name='report_dynamic_money'),
    path('report_credit_category', report_credit_category, name='report_credit_category'),
    path('report_debit_credit_line', report_debit_credit_line, name='report_debit_credit_line'),
    path('report_debit_credit_bar', report_debit_credit_bar, name='report_debit_credit_bar'),

]

mymoney/mymoney/urls.py
from django.contrib import admin
from django.urls import path, include

from money.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('money.urls')),
]

mymoney/money/models.py
from django.db import models


# Create your models here.

class Document(models.Model):
    type = models.IntegerField(blank=True, null=True)
    date = models.DateTimeField()
    sum = models.DecimalField(max_digits=10, decimal_places=2)
    sum_reg = models.DecimalField(max_digits=10, decimal_places=2)
    counterparty = models.ForeignKey('Counterparty', on_delete=models.PROTECT, blank=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, blank=True)
    currencie = models.ForeignKey('Currencies', on_delete=models.PROTECT, blank=True)
    active = models.BooleanField(default=True)
    comment = models.CharField(max_length=255, blank=True)
    account = models.ForeignKey('MoneyAccount', on_delete=models.PROTECT, blank=True)
    sum_reg_val = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        indexes = [
            models.Index(fields=['-date'])
        ]


class Counterparty(models.Model):
    name = models.CharField(max_length=255)
    comment = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    comment = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name


class Currencies(models.Model):
    code = models.CharField(max_length=3, db_index=True, primary_key=True)
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class TypeDebit(models.Model):
    name = models.CharField(max_length=255)
    comment = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class TypeCredit(models.Model):
    name = models.CharField(max_length=255)
    comment = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class MoneyAccount(models.Model):
    name = models.CharField(max_length=255)
    type = models.IntegerField(default=1, blank=True, null=True)  # 0- cash 1- Bank account
    currencie = models.ForeignKey('Currencies', on_delete=models.PROTECT)
    comment = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name

class ExchangeRates(models.Model):
    currencie = models.ForeignKey('Currencies', on_delete=models.PROTECT)
    date = models.DateField()
    value = models.DecimalField('value', null=False, max_digits=10, decimal_places=5,default=0)
    multiplicity = models.IntegerField(blank=True, default=0)

    class Meta:
        indexes = [
            models.Index(fields=['-date'])
        ]

class SettingPage(models.Model):
    name_page = models.CharField(max_length=255)
    value = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name_page

mymoney/money/views.py
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.datetime_safe import date
from django.views.generic import ListView, CreateView

from .forms import ExchangeRatesForm, DebitDocForm, CreditDocForm, CounterpartyForm, CurrencieForm, CategoryForm, \
    MoneyAccountForm, ReportForm
from .models import *
from .report_utils import *
from .utils import *


def index(request):
    account_sum_list = Document.objects.all() \
        .values('account__name', 'currencie__name', 'currencie__code') \
        .annotate(Sum('sum_reg')) \
        .filter(active=True)

    list_sum = list(account_sum_list)
    total = 0
    total_usd = 0
    current_date = date.today()

    for item in list_sum:
        total = total + get_regulated_sum(current_date, get_currencie_by_code(item['currencie__code']),
                                          item['sum_reg__sum'])

    total_manage = get_managerial_sum(current_date, get_manage_currencie(), total)
    total = f"{round(total, 1):,}"
    total_manage = f"{round(total_manage, 1):,}"
    context = {
        'data_list': account_sum_list,
        'total': total,
        'total_manage': total_manage,
        'main_currencie': get_main_currencie(),
        'manage_currencie': get_manage_currencie()
    }

    return render(request, 'money/index.html', context)


class DocumentList(ListView):
    template_name = 'money/documents.html'
    paginate_by = 50

    def get_queryset(self, **kwargs):
        return Document.objects.all().order_by('-id')


def show_doc(request, doc_id):
    doc = get_object_or_404(Document, pk=doc_id)

    doc_type = doc.type
    doc_name = ""
    if request.method == 'POST':
        if doc_type == 1:
            form = DebitDocForm(request.POST)
            doc_name = "Приход"

        elif doc_type == 2:
            form = CreditDocForm(request.POST)
            doc_name = "Расход"

        if form.is_valid():
            try:
                doc.date = form.cleaned_data.get('date')
                doc.sum = form.cleaned_data.get('sum')
                currencie = get_object_or_404(MoneyAccount, pk=form.cleaned_data["account"].id).currencie
                doc.currencie = currencie
                doc.counterparty = form.cleaned_data.get('counterparty')
                doc.category = form.cleaned_data.get('category')
                doc.account = form.cleaned_data.get('account')
                doc.active = form.cleaned_data.get('active')
                doc.comment = form.cleaned_data.get('comment')
                reg_sum = get_regulated_sum(doc.date, doc.currencie, doc.sum)
                if doc_type == 1:
                    doc.sum_reg_val = reg_sum
                    doc.sum_reg = form.cleaned_data.get('sum')
                else:
                    doc.sum_reg_val = reg_sum * (-1)
                    doc.sum_reg = form.cleaned_data.get('sum') * (-1)
                doc.save()

                return redirect('docs')
            except:
                form.add_error(None, 'Ошибка добавления')
    else:

        if doc_type == 1:
            form = DebitDocForm()
            doc_name = "Приход"
        elif doc_type == 2:
            form = CreditDocForm()
            doc_name = "Расход"
        form.fields["date"].initial = doc.date
        form.fields["sum"].initial = doc.sum
        form.fields["sum_reg"].initial = doc.sum_reg
        form.fields["counterparty"].initial = doc.counterparty
        form.fields["category"].initial = doc.category
        form.fields["account"].initial = doc.account
        form.fields["active"].initial = doc.active
        form.fields["comment"].initial = doc.comment
        form.fields["sum_reg_val"].initial = doc.sum_reg_val

    context = {
        'doc_id': doc_id,
        'form': form,
        'doc_name': doc_name
    }

    return render(request, 'money/document.html', context)


def add_debit_doc(request):
    if request.method == 'POST':
        form = DebitDocForm(request.POST)
        if form.is_valid():
            try:
                currencie = get_object_or_404(MoneyAccount, pk=form.cleaned_data["account"].id).currencie

                form.cleaned_data["type"] = 1
                form.cleaned_data["sum_reg"] = form.cleaned_data["sum"]
                form.cleaned_data["sum_reg_val"] = get_regulated_sum(form.cleaned_data["date"],
                                                                     currencie,
                                                                     form.cleaned_data["sum"])
                new_doc = Document(**form.cleaned_data)
                new_doc.currencie = currencie
                new_doc.save()

                return redirect('docs')
            except Exception as e:
                form.add_error(None, str(e))
                print(str(e))
    else:
        form = DebitDocForm()
        form.fields["date"].initial = timezone.now().date()

    context = {
        'form': form
    }
    return render(request, 'money/add_debit.html', context)


def add_credit_doc(request):
    if request.method == 'POST':
        form = CreditDocForm(request.POST)
        if form.is_valid():
            try:
                currencie = get_object_or_404(MoneyAccount, pk=form.cleaned_data["account"].id).currencie
                form.cleaned_data["type"] = 2
                form.cleaned_data["sum_reg"] = form.cleaned_data["sum"] * (-1)
                form.cleaned_data["sum_reg_val"] = get_regulated_sum(form.cleaned_data["date"],
                                                                     currencie,
                                                                     form.cleaned_data["sum"]) * (-1)

                new_doc = Document(**form.cleaned_data)
                new_doc.currencie = currencie
                new_doc.save()
                return redirect('docs')
            except Exception as e:
                form.add_error(None, str(e))
                print(str(e))
    else:
        form = CreditDocForm()
        form.fields["date"].initial = timezone.now().date()

    context = {
        'form': form
    }
    return render(request, 'money/add_credit.html', context)


def delete_doc(request, doc_id):
    try:
        instance = Document.objects.get(id=doc_id)
        instance.delete()
        return redirect('docs')
    except:
        print('Ошибка удаления документа')
    return render(request)


def directories(request):
    return render(request, 'money/directories.html')


class CounterpartyList(ListView):
    template_name = 'money/counterpartys.html'
    paginate_by = 50

    def get_queryset(self, **kwargs):
        return Counterparty.objects.all()


class ExchangeRatesList(ListView):
    template_name = 'money/exchangerates.html'

    def get_queryset(self, **kwargs):
        return ExchangeRates.objects.all()


class AddExchangeRates(DataMixin, CreateView):
    form_class = ExchangeRatesForm
    template_name = 'money/add_rate.html'
    success_url = reverse_lazy('rates_list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))


def show_rate(request, rate_id):
    rate = get_object_or_404(ExchangeRates, pk=rate_id)
    if request.method == 'POST':
        form = ExchangeRatesForm(request.POST, instance=rate)
        if form.is_valid():
            form.save()
            return redirect('rates_list')
    else:
        form = ExchangeRatesForm(instance=rate)

    context = {
        'rate_id': rate_id,
        'form': form,
    }
    return render(request, 'money/rate.html', context)


def delete_rate(request, rate_id):
    try:
        instance = ExchangeRates.objects.get(id=rate_id)
        instance.delete()
        return redirect('rates_list')
    except:
        print('Ошибка удаления курса валют')
    return render(request)


def show_counterparty(request, contr_id):
    rate = get_object_or_404(Counterparty, pk=contr_id)
    if request.method == 'POST':
        form = CounterpartyForm(request.POST, instance=rate)
        if form.is_valid():
            form.save()
            return redirect('ctr_list')
    else:
        form = CounterpartyForm(instance=rate)

    context = {
        'contr_id': contr_id,
        'form': form,
    }
    return render(request, 'money/counterparty.html', context)


def delete_counterparty(request, contr_id):
    try:
        instance = Counterparty.objects.get(id=contr_id)
        instance.delete()
        return redirect('ctr_list')
    except:
        print('Ошибка удаления курса валют')
    return render(request)


class AddCounterpartyForm(DataMixin, CreateView):
    form_class = CounterpartyForm
    template_name = 'money/add_counterparty.html'
    success_url = reverse_lazy('ctr_list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))


class AddCurrencieForm(DataMixin, CreateView):
    form_class = CurrencieForm
    template_name = 'money/add_currencie.html'
    success_url = reverse_lazy('cur_list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))


class CurrenciesList(ListView):
    template_name = 'money/currencies.html'

    def get_queryset(self, **kwargs):
        return Currencies.objects.all()


def delete_currencie(request, curr_id):
    try:
        instance = Currencies.objects.get(code=curr_id)
        instance.delete()
        return redirect('cur_list')
    except:
        print('Ошибка удаления валюты')
    return render(request)

mymoney/money/templates/money/add_category.html
{% extends 'money/base.html' %}
{% block content %}


<form action="{% url 'add_category' %}" method="post">
    {% csrf_token %}

    <div class="form-group col-md-2">
        <label for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
        {{ form.name }}
    </div>
     <div class="form-group col-md-10">
        <label for="{{ form.comment.id_for_label}}">{{form.comment.label}}</label>
        {{ form.comment }}
    </div>

    <br>
    <button type="submit" class="btn btn-primary mb-3 ">Сохранить</button>

</form>
{% endblock%}

mymoney/money/templates/money/add_moneyaccount.html
{% extends 'money/base.html' %}
{% block content %}


<form action="{% url 'add_monacc' %}" method="post">
    {% csrf_token %}

    <div class="form-group col-md-2">
        <label for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
        {{ form.name }}
    </div>

    <div class="form-group col-md-1">
        <label for="{{ form.currencie.id_for_label}}">{{form.currencie.label}}</label>
        {{ form.currencie }}
    </div>

    <div class="form-group col-md-10">
        <label for="{{ form.comment.id_for_label}}">{{form.comment.label}}</label>
        {{ form.comment }}
    </div>

    <br>
    <button type="submit" class="btn btn-primary mb-3 ">Сохранить</button>

</form>
{% endblock%}

mymoney/money/templates/money/add_rate.html
{% extends 'money/base.html' %}
{% block content %}


<form action="{% url 'add_rate' %}" method="post">
    {% csrf_token %}

    <div class="form-group col-md-2">
        <label for="{{ form.date.id_for_label }}">{{form.date.label}}</label>
        {{ form.date }}
    </div>
    <div class="form-group col-md-1">
        <label for="{{ form.currencie.id_for_label}}">{{form.currencie.label}}</label>
        {{ form.currencie }}
    </div>
    <div class="form-group col-md-2">
        <label for="{{ form.value.id_for_label }}">{{form.value.label}}</label>
        {{ form.value }}
    </div>

    <br>
    <button type="submit" class="btn btn-primary mb-3 ">Сохранить</button>

</form>
{% endblock%}

mymoney/money/templates/money/category.html
{% extends 'money/base.html' %}
{% block content %}


<form action="{% url 'show_category' category_id %}" method="post">
    {% csrf_token %}

    <div class="form-group col-md-2">
        <label for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
        {{ form.name }}
    </div>
    <div class="form-group col-md-10">
        <label for="{{ form.comment.id_for_label}}">{{form.comment.label}}</label>
        {{ form.comment }}
    </div>

    <br>
    <button type="submit" class="btn btn-primary mb-3 ">Сохранить</button>
    <button type="button" class="btn btn-danger mb-3" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">
        Удалить
    </button>

</form>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Удалить запись?</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-footer">
                <form action="{% url 'delete_category' category_id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">Ok</button>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

mymoney/money/templates/money/categorys.html
{% extends 'money/base.html' %}
{% block content %}
{% load static %}

<a href="{% url 'add_category' %}">Добавить</a>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Комментарий</th>
        </tr>
        </thead>
        <tbody>
        {% for m in category_list %}
        <tr>
            <td><a href="{% url 'show_category' m.id %}">{{m.name}}</a></td>
            <td>{{m.comment}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</main>
</div>
</div>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>

        {% endif %}
        {% if page_obj.has_other_pages %}
        {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-item"></li>
        <li class="page-item disabled">
            <a class="page-link">{{ p }}</a>
        </li>

        {% elif p >= page_obj.number|add:-6 and p <= page_obj.number|add:6 %}
        <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}
        {% endif %}

        {% if page_obj.has_next %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        {% endif %}

    </ul>
</nav>

{% endblock%}

mymoney/money/templates/money/counterparty.html
{% extends 'money/base.html' %}
{% block content %}


<form action="{% url 'show_counterparty' contr_id %}" method="post">
    {% csrf_token %}

    <div class="form-group col-md-2">
        <label for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
        {{ form.name }}
    </div>
    <div class="form-group col-md-10">
        <label for="{{ form.comment.id_for_label}}">{{form.comment.label}}</label>
        {{ form.comment }}
    </div>

    <br>
    <button type="submit" class="btn btn-primary mb-3 ">Сохранить</button>
    <button type="button" class="btn btn-danger mb-3" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">
        Удалить
    </button>

</form>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Удалить запись?</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-footer">
                <form action="{% url 'delete_counterparty' contr_id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">Ok</button>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

mymoney/money/templates/money/documents.html
{% extends 'money/base.html' %}
{% block content %}
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'add_debit_doc' %}">Приход</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'add_credit_doc' %}">Расход</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
               <a data-bs-toggle="offcanvas" href="#offcanvasRight" role="button"
               aria-controls="offcanvasExample">
                <img src="{% static 'money/images/list.png' %}">
            </a>
        </div>
    </div>
</nav>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel">Offcanvas right</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        ...
    </div>
</div>


<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Date</th>
            <th scope="col">Счет/касса</th>
            <th scope="col">Контрагент</th>
            <th scope="col">Сумма</th>
            <th scope="col">Валюта</th>
        </tr>
        </thead>
        <tbody>

        {% for m in document_list %}
        <tr>
            <td>
                {% if m.sum_reg < 0 %}
                <img src="{% static 'money/images/minus.png' %}" height="15">
                {% else %}
                <img src="{% static 'money/images/plus.png' %}" height="15">
                {% endif %}
                <a href="{% url 'show_doc' m.id %}">{{m.id}} </a></td>
            <td>{{m.date|date:"Y-m-d"}}</td>

            <td>{{m.account}}</td>
            <td>{{m.counterparty}}</td>
            {% if m.sum_reg < 0 %}
            <td style="color:red;">{{m.sum_reg}}</td>
            {% else %}
            <td style="color:limegreen;">{{m.sum_reg}}</td>
            {% endif %}
            <td>{{m.currencie}}</td>
        </tr>
        {% endfor %}


        </tbody>
    </table>
</div>
</main>
</div>
</div>


<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>

        {% endif %}
        {% if page_obj.has_other_pages %}
        {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-item"></li>
        <li class="page-item disabled">
            <a class="page-link">{{ p }}</a>
        </li>

        {% elif p >= page_obj.number|add:-6 and p <= page_obj.number|add:6 %}
        <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}
        {% endif %}

        {% if page_obj.has_next %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        {% endif %}

    </ul>
</nav>

        <script>
            const docOffcanvas =
                document.getElementById('offcanvasRight')

            docOffcanvas.addEventListener('show.bs.offcanvas', () => {
                //console.log('show instance method fired!');
            })

            docOffcanvas.addEventListener('shown.bs.offcanvas', () => {
                //console.log('offcanvas element completely visible!');
            })

            docOffcanvas.addEventListener('hide.bs.offcanvas', () => {
                //console.log('hide instance method fired!');
            })

            docOffcanvas.addEventListener('hidden.bs.offcanvas', () => {
                //console.log('offcanvas element completely hidden!');
            })
        </script>

{% endblock%}

mymoney/money/templates/money/moneyaccounts.html
{% extends 'money/base.html' %}
{% block content %}
{% load static %}

<a href="{% url 'add_monacc' %}">Добавить</a>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Валюта</th>
        </tr>
        </thead>
        <tbody>
        {% for m in moneyaccount_list %}
        <tr>
            <td><a href="{% url 'show_monacc' m.id %}">{{m.name}}</a></td>
            <td>{{m.currencie}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</main>
</div>
</div>


{% endblock%}

mymoney/money/templates/money/report_debit_credit.html
{% extends 'money/base.html' %}

{% block content %}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


<form class="row g-3" action="" method="post">
    {% csrf_token %}
  <div class="col-auto">
    <label  class="visually-hidden">Период с</label>
    {{ form.date_start }}
  </div>
  <div class="col-auto">
    <label class="visually-hidden">по</label>
    {{ form.date_end }}
  </div>

  <div class="col-auto">
   {{ form.listparam1 }}
  </div>
  <div class="col-auto">
    <button type="submit" class="btn btn-primary mb-2">Сформировать</button>
  </div>

  <canvas id="line-chart" width="50" height="20"></canvas>

</form>

{% autoescape off %}
<script>


new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {{ data }},
  options: {
    responsive: true,
    plugins: {
      legend: {
        position: 'top',
      },
      title: {
        display: true,
        text: 'Дебит/Кредит '
      }
    }
  },
});
</script>

{% endautoescape %}
{% endblock %}